<?php
return array (
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_blank',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'sort' => '906',
    'from' => 'iva',
    'show' => 'H5自带解析',
    'des' => 'videojj.com',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'xigua' => 
  array (
    'status' => '1',
    'from' => 'xigua',
    'show' => '西瓜影音',
    'des' => 'xigua.com',
    'ps' => '0',
    'parse' => '',
    'sort' => '712',
    'tip' => '<a href="//union.maccms.com/html/xigua.html" target="_blank">需要下载西瓜影音播放器</a>',
    'id' => 'xigua',
  ),
  'xfplay' => 
  array (
    'status' => '1',
    'sort' => '711',
    'from' => 'xfplay',
    'show' => '先锋影音',
    'des' => 'xfplay.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/xfplay.html" target="_blank">需要下载先锋影音播放器</a>',
    'id' => 'xfplay',
  ),
  'jjvod' => 
  array (
    'status' => '1',
    'sort' => '710',
    'from' => 'jjvod',
    'show' => '吉吉影音',
    'des' => 'jijizy.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '<a href="//union.maccms.com/html/jjvod.html" target="_blank">需要下载吉吉影音播放器</a>',
    'id' => 'jjvod',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷视频',
    'des' => 'youku.com',
    'ps' => '1',
    'parse' => '',
    'sort' => '618',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  '56_' => 
  array (
    'status' => '1',
    'sort' => '617',
    'from' => '56_',
    'show' => '我乐视频',
    'des' => '56.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => '56_',
  ),
  'tudou' => 
  array (
    'status' => '1',
    'sort' => '616',
    'from' => 'tudou',
    'show' => '土豆视频',
    'des' => 'tudou.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'tudou',
  ),
  'ku6' => 
  array (
    'status' => '1',
    'sort' => '615',
    'from' => 'ku6',
    'show' => '酷6视频',
    'des' => 'ku6.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'ku6',
  ),
  'qq' => 
  array (
    'status' => '1',
    'sort' => '614',
    'from' => 'qq',
    'show' => '腾讯视频',
    'des' => 'v.qq.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'sort' => '613',
    'from' => 'sohu',
    'show' => '搜狐视频',
    'des' => 'v.sohu.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'joy' => 
  array (
    'status' => '1',
    'sort' => '612',
    'from' => 'joy',
    'show' => '激动网',
    'des' => 'joy.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'joy',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'sort' => '611',
    'from' => 'qiyi',
    'show' => '奇艺视频',
    'des' => 'qiyi.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'letv' => 
  array (
    'status' => '1',
    'sort' => '610',
    'from' => 'letv',
    'show' => '乐视视频',
    'des' => 'letv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
  'funshion' => 
  array (
    'status' => '1',
    'sort' => '609',
    'from' => 'funshion',
    'show' => '风行视频',
    'des' => 'funshion.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'funshion',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'sort' => '608',
    'from' => 'mgtv',
    'show' => '芒果tv',
    'des' => 'mgtv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'wasu' => 
  array (
    'status' => '1',
    'sort' => '607',
    'from' => 'wasu',
    'show' => '华数tv',
    'des' => 'wasu.cn',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'wasu',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'sort' => '602',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => 'pptv.com',
    'parse' => '',
    'ps' => '1',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'fantasy' => 
  array (
    'status' => '1',
    'sort' => '601',
    'from' => 'fantasy',
    'show' => '范特西云视频',
    'des' => '范特西',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'fantasy',
  ),
);