<?php

return array(
    // Default AI Provider
    array(
        'name'    => 'default_provider',
        'title'   => lang('AI Provider'),
        'type'    => 'select',
        'content' => array(
            'claude'   => lang('Claude (Anthropic)'),
            'openai'   => lang('OpenAI (GPT)'),
            'gemini'   => lang('Google Gemini'),
            'deepseek' => lang('DeepSeek'),
            'qwen'     => lang('Alibaba Qwen'),
            'glm'      => lang('Zhipu GLM'),
        ),
        'value'   => 'claude',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('Default AI provider for content generation.'),
        'ok'      => '',
        'extend'  => 'id="ai-provider-select" lay-filter="ai-provider-select"',
    ),
    // Default Model
    array(
        'name'    => 'default_model',
        'title'   => lang('Model Name'),
        'type'    => 'string',
        'content' => array(),
        'value'   => 'claude-sonnet-4-6',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('Claude: claude-sonnet-4-6 | OpenAI: gpt-4o | Gemini: gemini-2.0-flash | DeepSeek: deepseek-chat | Qwen: qwen-turbo | GLM: glm-4'),
        'ok'      => '',
        'extend'  => '',
    ),

    // --- API Keys ---
    array(
        'name'    => 'claude_key',
        'title'   => lang('Claude Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('Anthropic API key (console.anthropic.com)'),
        'ok'      => '',
        'extend'  => 'data-provider="claude"',
    ),
    array(
        'name'    => 'openai_key',
        'title'   => lang('OpenAI Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('OpenAI API key (platform.openai.com)'),
        'ok'      => '',
        'extend'  => 'data-provider="openai"',
    ),
    array(
        'name'    => 'gemini_key',
        'title'   => lang('Gemini Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('Google AI Studio API key (aistudio.google.com)'),
        'ok'      => '',
        'extend'  => 'data-provider="gemini"',
    ),
    array(
        'name'    => 'deepseek_key',
        'title'   => lang('DeepSeek Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('DeepSeek platform API key (platform.deepseek.com)'),
        'ok'      => '',
        'extend'  => 'data-provider="deepseek"',
    ),
    array(
        'name'    => 'qwen_key',
        'title'   => lang('Qwen Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('Alibaba DashScope API key (dashscope.console.aliyun.com)'),
        'ok'      => '',
        'extend'  => 'data-provider="qwen"',
    ),
    array(
        'name'    => 'glm_key',
        'title'   => lang('GLM Key'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '',
        'rule'    => '',
        'msg'     => '',
        'tip'     => lang('Zhipu AI API key (open.bigmodel.cn)'),
        'ok'      => '',
        'extend'  => 'data-provider="glm"',
    ),

    // --- Generation Settings ---
    array(
        'name'    => 'max_tokens',
        'title'   => lang('Max Tokens'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '1500',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('Max tokens in AI response. Recommended: 800-2000.'),
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'batch_size',
        'title'   => lang('Batch Size'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '10',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('Items per batch job.'),
        'ok'      => '',
        'extend'  => '',
    ),
    array(
        'name'    => 'request_timeout',
        'title'   => lang('Timeout (s)'),
        'type'    => 'string',
        'content' => array(),
        'value'   => '30',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('HTTP timeout in seconds for AI API calls.'),
        'ok'      => '',
        'extend'  => '',
    ),

    // --- Output Language ---
    array(
        'name'    => 'language',
        'title'   => lang('Language'),
        'type'    => 'select',
        'content' => array(
            'zh-cn' => lang('Chinese Simplified (简体中文)'),
            'zh-tw' => lang('Chinese Traditional (繁體中文)'),
            'en-us' => lang('English'),
            'ko-kr' => lang('Korean (한국어)'),
            'ja-jp' => lang('Japanese (日本語)'),
            'de-de' => lang('German (Deutsch)'),
            'fr-fr' => lang('French (Français)'),
            'es-es' => lang('Spanish (Español)'),
            'pt-pt' => lang('Portuguese (Português)'),
        ),
        'value'   => 'zh-cn',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => lang('Language for AI generated content.'),
        'ok'      => '',
        'extend'  => '',
    ),

);
